services:
  questdb:
    image: questdb/questdb:8.2.2
    container_name: questdb-main
    ports:
      - 9000:9000
      - 9009:9009
      - 8812:8812
      - 9003:9003
    volumes:
      - ./questdb/questdb_root:/var/lib/questdb/:rw
    environment:
      - QDB_LINE_TCP_WRITER_WORKER_COUNT=2
      - QDB_LINE_TCP_IO_WORKER_COUNT=2
      - QDB_PG_READONLY_USER_ENABLED=true
  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana_alerts
  #   restart: always
  #   ports:
  #     - 3001:3000
  #   networks:
  #     - questdb
  #   volumes:
  #     - ./data/grafana:/var/lib/grafana/
  #     - ./grafana/provisioning/:/etc/grafana/provisioning/
